server:
  port: 19095

spring:
  application:
    name: auth-service
  profiles:
    active: local
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: URL=jdbc:mariadb://localhost:33062/connetrip?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: s5554549
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  security:
    oauth2:
      success-redirect: http://localhost:5173
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            client-authentication-method: client_secret_post
            redirect-uri: ${KAKAO_REDIRECT_URI}
            authorization-grant-type: authorization_code
            client-name: kakao
            scope:
              - profile_nickname
              - profile_image
              - account_email
      provider:
        kakao:
          authorization-uri: https://kauth.kakao.com/oauth/authorize
          token-uri: https://kauth.kakao.com/oauth/token
          user-info-uri: https://kapi.kakao.com/v2/user/me
          user-name-attribute: id

security:
  jwt:
    secret-key: afdakfjlkasjfaioefjklasfmakl;fjaklfmakl;dfaklfadsflka
    access-expired: 987654321
    refresh-expired: 987654321
